/*
  Animation Gallery
  100 animation definitions
*/

const ANIMATION_TYPES = [
  { id: "fade-in", name: "Fade In", category: "Entrance", description: "Opacity gradually increases." },
  { id: "fade-out", name: "Fade Out", category: "Exit", description: "Opacity gradually decreases." },
  { id: "slide-in-left", name: "Slide In Left", category: "Entrance", description: "Slides in from the left." },
  { id: "slide-in-right", name: "Slide In Right", category: "Entrance", description: "Slides in from the right." },
  { id: "slide-in-up", name: "Slide In Up", category: "Entrance", description: "Slides upward into view." },
  { id: "slide-in-down", name: "Slide In Down", category: "Entrance", description: "Slides downward into view." },
  { id: "slide-out-left", name: "Slide Out Left", category: "Exit", description: "Slides left and disappears." },
  { id: "slide-out-right", name: "Slide Out Right", category: "Exit", description: "Slides right and disappears." },
  { id: "slide-out-up", name: "Slide Out Up", category: "Exit", description: "Slides upward and disappears." },
  { id: "slide-out-down", name: "Slide Out Down", category: "Exit", description: "Slides downward and disappears." },
  { id: "zoom-in", name: "Zoom In", category: "Entrance", description: "Scales up into view." },
  { id: "zoom-out", name: "Zoom Out", category: "Exit", description: "Scales down and disappears." },
  { id: "zoom-in-bounce", name: "Zoom In Bounce", category: "Entrance", description: "Zooms in with a bounce." },
  { id: "zoom-out-bounce", name: "Zoom Out Bounce", category: "Exit", description: "Zooms out with a bounce." },
  { id: "bounce", name: "Bounce", category: "Attention", description: "Bounces vertically." },
  { id: "bounce-in", name: "Bounce In", category: "Entrance", description: "Enters with a bounce." },
  { id: "bounce-in-left", name: "Bounce In Left", category: "Entrance", description: "Bounces in from the left." },
  { id: "bounce-in-right", name: "Bounce In Right", category: "Entrance", description: "Bounces in from the right." },
  { id: "bounce-in-up", name: "Bounce In Up", category: "Entrance", description: "Bounces upward into view." },
  { id: "bounce-in-down", name: "Bounce In Down", category: "Entrance", description: "Bounces downward into view." },
  { id: "pulse", name: "Pulse", category: "Attention", description: "Gently grows and shrinks." },
  { id: "heartbeat", name: "Heartbeat", category: "Attention", description: "Beats like a heart." },
  { id: "flash", name: "Flash", category: "Attention", description: "Flashes repeatedly." },
  { id: "flicker", name: "Flicker", category: "Attention", description: "Flickers irregularly." },
  { id: "shake", name: "Shake", category: "Attention", description: "Shakes side to side." },
  { id: "shake-x", name: "Shake X", category: "Attention", description: "Shakes horizontally." },
  { id: "shake-y", name: "Shake Y", category: "Attention", description: "Shakes vertically." },
  { id: "wobble", name: "Wobble", category: "Attention", description: "Wobbles around its center." },
  { id: "swing", name: "Swing", category: "Attention", description: "Swings from its top edge." },
  { id: "tada", name: "Tada", category: "Attention", description: "Rotates and scales with emphasis." },
  { id: "rubber-band", name: "Rubber Band", category: "Attention", description: "Stretches and snaps back." },
  { id: "jello", name: "Jello", category: "Attention", description: "Wobbles with a jelly-like effect." },
  { id: "rotate-in", name: "Rotate In", category: "Entrance", description: "Rotates into view." },
  { id: "rotate-out", name: "Rotate Out", category: "Exit", description: "Rotates away." },
  { id: "rotate-in-left", name: "Rotate In Left", category: "Entrance", description: "Rotates in from the left." },
  { id: "rotate-in-right", name: "Rotate In Right", category: "Entrance", description: "Rotates in from the right." },
  { id: "rotate-in-up", name: "Rotate In Up", category: "Entrance", description: "Rotates in from above." },
  { id: "rotate-in-down", name: "Rotate In Down", category: "Entrance", description: "Rotates in from below." },
  { id: "flip-x", name: "Flip X", category: "3D", description: "Flips around the horizontal axis." },
  { id: "flip-y", name: "Flip Y", category: "3D", description: "Flips around the vertical axis." },
  { id: "flip-in-x", name: "Flip In X", category: "Entrance", description: "Flips into view on the X axis." },
  { id: "flip-in-y", name: "Flip In Y", category: "Entrance", description: "Flips into view on the Y axis." },
  { id: "flip-out-x", name: "Flip Out X", category: "Exit", description: "Flips away on the X axis." },
  { id: "flip-out-y", name: "Flip Out Y", category: "Exit", description: "Flips away on the Y axis." },
  { id: "hinge", name: "Hinge", category: "Exit", description: "Swings down and exits." },
  { id: "jack-in-the-box", name: "Jack In The Box", category: "Entrance", description: "Rotates and pops into place." },
  { id: "roll-in", name: "Roll In", category: "Entrance", description: "Rolls into view." },
  { id: "roll-out", name: "Roll Out", category: "Exit", description: "Rolls out of view." },
  { id: "light-speed-in", name: "Light Speed In", category: "Entrance", description: "Rushes in with a skew." },
  { id: "light-speed-out", name: "Light Speed Out", category: "Exit", description: "Rushes away with a skew." },
  { id: "rubber-pop", name: "Rubber Pop", category: "Attention", description: "Pops larger then settles." },
  { id: "float", name: "Float", category: "Loop", description: "Gently floats up and down." },
  { id: "hover-lift", name: "Hover Lift", category: "Interaction", description: "Lifts upward on hover." },
  { id: "hover-tilt", name: "Hover Tilt", category: "Interaction", description: "Tilts on hover." },
  { id: "hover-grow", name: "Hover Grow", category: "Interaction", description: "Grows on hover." },
  { id: "hover-shrink", name: "Hover Shrink", category: "Interaction", description: "Shrinks on hover." },
  { id: "hover-glow", name: "Hover Glow", category: "Interaction", description: "Glows on hover." },
  { id: "hover-spin", name: "Hover Spin", category: "Interaction", description: "Spins on hover." },
  { id: "hover-bob", name: "Hover Bob", category: "Interaction", description: "Bobs vertically on hover." },
  { id: "hover-skew", name: "Hover Skew", category: "Interaction", description: "Skews on hover." },
  { id: "hover-underline", name: "Hover Underline", category: "Interaction", description: "Underline animates into place." },
  { id: "shimmer", name: "Shimmer", category: "Loop", description: "A highlight sweeps across the element." },
  { id: "shine", name: "Shine", category: "Loop", description: "A diagonal shine passes across the surface." },
  { id: "gradient-shift", name: "Gradient Shift", category: "Loop", description: "Background gradient colors shift." },
  { id: "color-pulse", name: "Color Pulse", category: "Loop", description: "Background color pulses between tones." },
  { id: "neon-glow", name: "Neon Glow", category: "Loop", description: "A neon-like shadow pulses." },
  { id: "border-glow", name: "Border Glow", category: "Loop", description: "The border glow brightens and dims." },
  { id: "shadow-pulse", name: "Shadow Pulse", category: "Loop", description: "The drop shadow expands and contracts." },
  { id: "spin", name: "Spin", category: "Loop", description: "Rotates continuously." },
  { id: "spin-reverse", name: "Spin Reverse", category: "Loop", description: "Rotates continuously in reverse." },
  { id: "slow-spin", name: "Slow Spin", category: "Loop", description: "Rotates slowly." },
  { id: "swing-loop", name: "Swing Loop", category: "Loop", description: "Swings continuously." },
  { id: "pendulum", name: "Pendulum", category: "Loop", description: "Swings like a pendulum." },
  { id: "orbit", name: "Orbit", category: "Loop", description: "A marker orbits the center." },
  { id: "waves", name: "Waves", category: "Loop", description: "A wave-like scale effect repeats." }
];
